| com a1 a2 a3 a4 |

com := Comision new.

a1 := Alumno new.
a1 legajo: 101; nota: 8.

a2 := Alumno new.
a2 legajo: 102; nota: 6.

a3 := Alumno new.
a3 legajo: 103; nota: 4.

a4 := Alumno new.
a4 legajo: 104; nota: 2.

com inicializar.
com inscribirAlumno: a1; inscribirAlumno: a2; inscribirAlumno: a3;inscribirAlumno: a4 .
Transcript clear.
com alumnosMayProm.
com alumnosMayMitadProm.
com alumnosMenProm.

